apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-cronjob
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-cronjob
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-cronjob
subjects:
  - kind: ServiceAccount
    name: api-cronjob
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: api-cronjob
