---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone-conf
  namespace: apps--backpan-syncer
spec:
  encryptedData:
    rclone.conf: AgBa1qdCa2wDJjCroFSLfdjhiuX0dIMCIOMyfvw/t5BlZ8YdkJTxHBY/K+/DBTerh3EfREc14fn4SJ2obZztOPENlq1gtXkxbt95040eD9blY/9gOhrcsiYlZCGsXIm4HUdAz0J4a/Cx/IMjcG9L2GOV5OHs82+fCI84vc7jiCv7FyPMP9Bj/RkOzVOgqdisjCPwtR6yqHcxGDrTbTnJZrl8onuqgvlVcboyKcSxvX/hjy6OG8le7g1to01cZzK6d9vFjHbYElBYl/CJQj0h5hsjBwXJdH0yMpyfjMsg9XLQPS4ks4smsj3Xm52/zA3UdTFkf0Z+joDbyMw/8iylXJqu5xlKbU26G84QSeBS7+YOH6WZO/MH8FZJGzY/unpinv+G4dvPKNyMiIiVHGPaFXOXFMjQA/9kPOIU1E0CKYsCDbV8TaNap1FuQatoypiA21Ism30rn+EOWWiot8ag43DMzQJk24SDaDWC/bmQKDqB0A9FLIeFsX4q9/PGu/0QHMPxilVStlmB0bxymFxztTLIDf9Q/g0x6gcV3eILCw0C8LtcvLqm/CFy/oNHjRK3KYvMW2LSnEG/mbd5FXUWqqEs5on3N21l/xuP3JfWOPR7W4N06npD5+UL2CkxN61bZ0SIDd2OM8sAij6x03wLmV/SY+Fr3R2G09yZfz64wdzwCXmOY3rL5+AQmHNyqVjMQjp1M32XYwP1uM+0u5fsf1qAb+u9sCbIAbmJ8EyxNDr9Qsf0LXLg2XtCs36Pl+i7fGAtrdPvp2zZaQrD7iYbu17bT1+90ttsJv6P68Tm641mtR5+P9+sKvED/TCNzpIwpnuQObtgFsZVaSpkiBz7CyPFA6qizRV+R8NefAsZ5rWLsE9g7M5++mGqQULPZ0VSZsH0SHcV/NB0VwjJKLTPNuIViWVGFjOUQ0V7VfvxevdrLWxBCGHdAofI8NT/oqAWnYTWHQOTpotpROkzlx6QxojSUkLeXCk6B7o2lMhgIOaWRwTb5fw34x7hzUP+3v7klg/LAo2Lac4/c+hfFoVSGP215RX64v8x886vmmv+6VEja+ztGk3aUd0JXrOarPdp9RBSY/JEj2SJfrTOceLJ7Qy+xTxtpBtnfm9C4HarM/gNHk1UU+cbavmjFP2dEYysH5qGAw==
  template:
    metadata:
      name: rclone-conf
      namespace: apps--backpan-syncer
