---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: datadog-api-key
  namespace: apps--datadog
spec:
  encryptedData:
    api-key: AgB2ZY4B21OjEpqm/ImRLF4SHXuwYFXYpzozDQIZw0aRrz9MvCGvmccB3JfVVA8D4QgEs8EfK2lQWGY4QhgKAaLLyhnNaGvoCy373bjiyuPDMZFxnNYez7jnk8PZJXOn02LeB9/89IsfkVml6ifky4Ry/tVA4Stg6uKTa/m/79HmVMiMJclQQ7dsSuOVSvAh0thE9qBhuPPMu8hUws6E6X18ZJLbC1hIx1Jxqjht27smdNjdeRnuyedmI42bjixqMPnieCMfhwmW6UTm2KNuEY/ovYbA1xj7w3PlEGYbcCuhISqpv4FftUM7iogwyvrMZy4sjh7nUHzRB/GX1fwWlLERAMPRGDP+1jNWshZfXO1oVQXaG0EXSLZNCM+4zM3AWIwThkIn7+ed2VnovxbNNAl1KqLSqlsFse7kOb4CquS+nXsLSWxmRAPbBNchdIPYq4QmeCnrR8eNNKLn/DFQY9OkrfeyYpTKMMBCSAfKR9TpFouAYI+EqsEjSJMy4b+0I7Fnok0AzrWiF4xxMgH96UPRFEwSds3L/4n2+2Y84onCNBKN6TZ4ZJgLIQU9CPSgnjDAVC0xL0QP9CTugBTOBEQW8UnSsh2d7G4YyPjNH+ozIEOZbARFORDvhfFuxDzpvF6bc9eeQTipbQpe3N4cxX8jRvpchXbJJcFob/n6OUmbpqIAwqz5dwBScqc8/HXa3pPjZNodSg1PP9UZvVPs1i1+o1VTkm+nB+3eMoAe1CBnAg==
  template:
    metadata:
      name: datadog-api-key
      namespace: apps--datadog
