---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rclone-conf
  namespace: apps--backpan-syncer
spec:
  encryptedData:
    rclone-conf: AgBK2d8AM1NB0YKrKgX0pHV0VFkDzT3t18EgnjecgH7Rk61VDJQLxBR282a/ovdzs3XaDzdN9Zp3PaVnDjIQXCDukN1HIh+l/KSYjDLnJtqi/t8/4iUnpfD3B7ljWfVexBnpOl47iV6Dt3LjIYYV/Bir28YPzrfzHw5TOLZWBzOVNYyuVrqJEvdgR1AkQ/E86oN8bBqcnQPVtG8GJ5b3ympd2mH24uDftes7vIAMsx9ow4VF7UbAz5w94ZEfStyHL+dQUudKZqn06477Hs50zN3k4PMfXhTI2cG9ldYa3f/AkT5r5LTOEMQEh6YzYOua/00U7xCey+ev3DhMraHVk5qRcpFVojf4W43uKGsbkt2FqgwIDSH+NnWyyvQQcvBNS7t7He+1vsCBT7MPLiCFrCaOLGJj8rC9PVwpjnR7bavO/VdkSui+zR8/2obIz0T+INnsHoHpMrrH65yxMh5AvSaEtcP6wTaYtppqsmmn/b62x6jsNtSgL51ZDFN6jwOJ7emyrPAeqm6KuCOP5sRKaWgvfOxcnF5jGotifVloWIzWE8/hFkv7ih5OdoLfNngVFmy3JvwdCimvYI6rP6eeOu47x3Guu8XlNNsu2NGpXmwQHS9CxQ+dZwAaKFG0jINRVe/3VXhoU6jSktdIQQykw6rIPLVzGAFmkVUokcxS5O/oTLFWoXh8NhlpppBqAFBuAnlos6hAyASbAREaQpD76J3CHD7PmCDl/fWmSHoIkHjmGiz3phvJLoPduX2aV5K/sXiG94+hSvhnsejqKj2CaauqikM0RJquX1dx4htLwjCTdxrY9bjLXey3B6AwMHiogLFZiJ7a6GrSoWfZTomV7Xv9j/OkNfkXxfhv5URUCpxrPqJ1eWE5ziLjRKU6gCXLrnRSnxyf3NbE+gdOj/kNJHTD8yQO/FRNMBgXxKAejYHBsXHYQ67XcLsbpK9qKcD3Xvqlwy5c4WHgKv2MYjyAp8bMch6ZHhDAe4Vi8Xe0jZZyCemCUzQmIodGmVxuMa32zL3ZkFawLBnDScY4Vakpd0ojKdwNUXHu5kS28Hhyty+aAmk7n6E3OCZCJk9M5b+Yes2hgg8IJOyc4CsvtfSA6Ho9nqUNJkf4OSXiPsPok8R3rT/meY2MmRZIkSUUbOQjF218Sg==
  template:
    metadata:
      creationTimestamp: null
      name: rclone-conf
      namespace: apps--backpan-syncer
