---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

  # https://raw.githubusercontent.com/jkpedo/rook/refs/heads/doks/deploy/examples/crds.yaml
  - crds.yaml
  # https://raw.githubusercontent.com/jkpedo/rook/refs/heads/doks/deploy/examples/common.yaml
  - common.yaml
  # https://raw.githubusercontent.com/jkpedo/rook/refs/heads/doks/deploy/examples/operator.yaml
  - operator.yaml


