apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps--mc-api
images:
- name: docker.io/metacpan/metacpan-api
  newTag: sha-914a6695f3ca907a8955ac202fb7b332378e0193
resources:
- prod_sealedsecret.yaml
- ingress.yaml
- ../../base/
