apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps--mc-api
images:
- name: docker.io/metacpan/metacpan-api
  newTag: sha-bc17fb487345b1e36f98fee96a1b9563c7443a1c
resources:
- prod_sealedsecret.yaml
- ingress.yaml
- ../../base/
