apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps--mc-api
images:
- name: docker.io/metacpan/metacpan-api
  newTag: sha-72cea1919a43dfbe7603967c7281d7ff9453212d
resources:
- prod_sealedsecret.yaml
- ingress.yaml
- ../../base/
