apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps--grep
resources:
- namespace.yaml
- ingress.yaml
- ../../base/
images:
- name: metacpan/metacpan-grep-front-end
  newTag: sha-9f02b9adbed1a9afd8d8cab88e36ff39ea7d718d
