apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps--grep
resources:
- namespace.yaml
- ingress.yaml
- ../../base/
images:
- name: metacpan/metacpan-grep-front-end
  newTag: sha-f53fee5cb00001295bdecbdcf8ae7b9af506a194
