apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps--grep
resources:
- namespace.yaml
- ingress.yaml
- ../../base/
images:
- name: metacpan/metacpan-grep-front-end
  newTag: sha-a8e8eec329d45cbd82a61c0cd65b4faa5d5ac9ce
