---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: apps--external-dns
spec:
  encryptedData:
    api-token: AgBT7OuaGluQxJsbXD5v+1jjZKHGEsAfAatxp3SDBuPVRInk4VjREvy8lfVY8KZzWB7MpElpv2SAu3CBTW81XbLBB8Be6LNHZ0kGezvR0ObH23nEAfhks/XYfOn1ymyLhAUu0Rb+PvH6+sxaXcFRV44ImNIOXrOp1NFl6BFX+pcMakUk9m0lU7Kos4JqoFku+hqIBis9551vXRxHZPM3CpvsrAJKFCPapl0MD0bz8b89Q+0wpslV1y4Q5WmzsjjLvvCchZI6pIWMA40vrknNenFV5LQhtGpHh0yLqPYfVUZJChjQra2G2LKWoFCsESXar+WPW/HiWkamVzoFwJfmGkixqhCioSp1r2V5rmjwitEfBNRs6Da/GU3PXu9+IB5Ncrw37DVgdTdm34QNrLgsdZ6fHtYqbKmmWjxUsXfOm7KU82th3zFP3eA7yXZfqHKVwaACPt7IN/YPEz1e2LuWO1V1OC9FfuyfFOkAKgz/0+uKQCFKLxtTk224vuV0NHGVeWIv6w6Eb23ZsF+kLW05PC1cvy1YulRTalbm7sFImMxb69M3SjoVSyJPM1e/b2dZJhHPCiA6w01x+pQDOkPopLM3Dza8TP1nEk0cUrNRrNNdEAqk7Xq3ZmG2my9f7qTSERjXF6ude0g+Xh/QEhkNG2ifHxpMJvLSFvFnbiUG/l96o0iFAB54qS63JsfN4lofDEEXlRi7TWTmtJrlJhSnUxdyoW2maRwNfHbYr6OfGGS88VM1BFSYch6o4PQk04ojhzRscCbrsQ==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: apps--external-dns
