apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps--web
images:
- name: docker.io/metacpan/metacpan-web
  newTag: sha-34a5570d4c1e7471e85f92b6b782413f8e485046
resources:
- fastly-api_sealedsecret.yaml
- purge-fastly-cache.yaml
- prod_sealedsecret.yaml
- namespace.yaml
- ingress.yaml
- ../../base/
