apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps--web
images:
- name: docker.io/metacpan/metacpan-web
  newTag: sha-18fc5b6892ca5fad2773fb6e18ee1398f2289597
resources:
- fastly-api_sealedsecret.yaml
- purge-fastly-cache.yaml
- prod_sealedsecret.yaml
- namespace.yaml
- ingress.yaml
- ../../base/
