apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps--web
images:
- name: docker.io/metacpan/metacpan-web
  newTag: sha-f2f67c33c65ed412b0652eaa4c33a6b5ce794db2
resources:
- fastly-api_sealedsecret.yaml
- purge-fastly-cache.yaml
- prod_sealedsecret.yaml
- namespace.yaml
- ingress.yaml
- ../../base/
