apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: extraction-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hcloud-volumes
  resources:
    requests:
      storage: 100Gi
