apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps--mc-api
images:
  - name: docker.io/metacpan/metacpan-api
    newTag: latest
resources:
  - namespace.yaml
  - ingress.yaml
  - ../../base/
patches:
  - target:
      kind: Deployment
      name: api
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
      - op: remove
        path: /spec/template/spec/volumes
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts
      - op: remove
        path: /spec/template/spec/containers/0/env
  - target:
      kind: Deployment
      name: api-search
    patch: |
      - op: replace
        path: /spec/replicas
        value: 0
