---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docker-local-yaml
  namespace: apps--testsmoke
spec:
  encryptedData:
    docker_local.yaml: AgB6mjnubWKjQsuBnDRgt5rhY6ySjrsQzIBzDOCB48Xu/kXRLpNZPFCGusnoWjb6jf9uOsmXrY3UT8dZjC5K4VjGLXDlCr6w93P8Cgfu41AoLjkaY3+LG7/1h5VBAIBD0NIQgayRVRO1oz6/b8pHBVaZWfG/7SSSQDMNSFpmz6C9lPFXf0j76FoP6cPywr934niK4P3uuXMm+VrhIge7pvbNFBiVJ1KKHAGNeefq+MdkZycWegP3PNhc65XSqfXixO2j/5qniTyU6r2hvd6pOKzujaW1FFD73fBcAHg9N4scfpxaFrFjOM6YBeyQnuA3OuIrdVlwArO0k/qD1hSfXxxPM5sZxA25qJthoetz1xndc3x++xwmNKEEnDKHrL3K4n7pQRN4mHXGU57yTZ9Kr8ymn1nVBxSIxUzptL+l3xGq7QcG4NlaF2BgdeYbZwFiuP3g1dUth6l/kfULCxIn2XinfuGsbP6szc96FsplYyTfw2GLpcddfy6G/dJ/3MOH4vIeCpqosE3S/qJpJRk6/+gHENU6j3F1l1PYwylH1vt9ji4QKf4oLqgakXi8nS387CPyGK5mzdT/QxtpB4CcM+lJlBSNPIeYD8qb8noZYnxMYkWzqmzRutcRFcxni7M5lkZsDs509Hajcy91HXMkPune3YixM3chyIy9ykLBHZxqPiDT/vIDE/VQEFrXOqXoTU8QXrw7ch1X/bMuF7MU4pKwQkEUok7LuYIt0IAyfQWcms809IbLY6vIjU72a3KSZtFNwdjGo/h3M8uYehBtooqY7ENcolcKG9DDTC/glJe1SauwbW8O3dU+0IbBd6Tn44O2AC9zBkLm/oVlHQsG1M1vh/XRmRct3YBxxFBI8K4FOYkYxxHT6NvvtaHFRxCrabaD34wXH3c+oGk2Zveh+hRv55SJpp0bCDMxs/UALzv4HD+QVq7hOuyXEbzpM8yE7WnH4yyTxRHoldPlv3GzcWhGuTCDfI35x7MP82EFPya5oPIo5Dg1ppIGeUt73nTwP7c18vSkoA9+tAN3j2Wl+X7cfNewGdaFSCQRpJHktEuPDyZyp9k/BJ++DA1p4GTDtsXNIVwzZ5AmXQKYx+3EZF8UPMWfwZuDDIvbTzk3DJ+RitgdUjzGguvKKD9qBdD0eS9kOIKHk35ZUXip7YFmxM4OAzHcNR4fqaZrhFX1td3MDv/5VmWwk5KoMGXN3BaRNVn4ULouxS+l8VYShzpvwkXldE5Ez2i5oZL/O1syTUF3BHbyaOTmnnvJAeYARZyP/cFRZomxtOBUTA0e5sDq7KfnVvXD/1s0NruK/vpspSSWhKNleWiLy541bYizq3+34M4P
  template:
    metadata:
      name: docker-local-yaml
      namespace: apps--testsmoke
