---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: metacpan-web-local
  namespace: apps--web
spec:
  encryptedData:
    metacpan_web_local.conf: AgATKF6wNIDYLJnEGmGCYmltdtknP2u2RRfh5yoQtqpaTgP1K1D/OtEfMvD1bWxAPCOUCegDXMDtXB6YWKLmZIgv6txef7zJXpTAXwWGangIRoi0Y75mZmaVW0ptcsmhxkkS/YWkIZuA0Vib6QlXM6HIvOlJ2y12gRBp87UeJId1FGcR0cFqGdZozBeBOvXuHBAtx0cy7KA62DhKiefQ/4Df9ljwkHgKPKn55VX70RE5WJuxVGJs+xRV0xP9LcPDhAB+/vtUtZooRwP29ghf9b6OfbgV2wLyH3kHlFSujK8Bkdx291GNEAvggmfoJloOu+yiNGDJyXGSp1Nu/bjWiwzgCsPjEViX+CR1PYOEN9HzlD7F2q9K9sBKFRVd7nMJH822M1+dzEd7bvOQPP+c0kfgTiqlc9/GBDqPHPMHDb6J0lB4pCiqRD7JnMZxrSnMM5rNtsh+d4yw1a9+B4WZGC1PoJFkiDfceKvhEbiw9zwkvfMfPOTummMIxZPDri7IFY3bQmysSkjKTfHZzTh8G31rwOHG/tcspTWLvCSGGX/91ON+rHiNkB8Oo+fQkaE4SG6iUSRZkeR80eOmxP3RHKPaOpDqasPjbtdWYmtKcNX563i/iY9+fgomFmTCUoQZWpJron3IvxIb6+wxBj3Vax/UNxelXDXBr/KbTBAPvXcoQJMhwtZG5mK4GKdQCAODEQWFdzWYko+UxQ0aZhVi1icUsqO/x8jxdU/fJDnQFo+o71ycbltjATCW6Z2SLRvG6RlvTII5zjC9r4IrGe9W0/uaMPICR3u3xt0VEq94hVJBU28vhAquP81DZC4QvF3VpCIZa38hIPGcvoiVZKvJcRGdGbizXjtM4D2dEc8HEL6Zxbtk1yRxShhaSxRdxKWkUDnumlU4EJTFAyYUGC2ZWitqr+SyylVXFKEDDFPy9IFTywZPKreHcb7NXd/oonG0Ab5DpsoafYajhob4sV1msFVQZbooLKH5kJniNm+AS3kVQC4upSvUgAZm/diZ7mWSy3uFBBAYfs4gqcFR2Zv1gwxF8CmhuLHC1AYMmnF4+vIx3LMCeKLzjKYGzjzb/79bIQ0AUcqmzWqg5gkXxMvQ9MLU2MX6WWnDNNlFq4lpWMA7xi6H5UtWT6PR/EPRUuNtJ9q3mtc4gsM41fX4SBHqb1PHWJAyiP36DZWJt3yooGjOoohyuNA=
  template:
    metadata:
      name: metacpan-web-local
      namespace: apps--web
