apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hz--api-v0-shim
  namespace: argocd
spec:
  project: api-v0-shim
  source:
    repoURL: https://github.com/metacpan/metacpan-k8s
    targetRevision: cloudfleet
    path: apps/api-v0-shim/environments/hz
  destination:
    server: https://kubernetes.default.svc
    namespace: apps--api-v0-shim
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
