---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: pg
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBLuTxO5bUjigaF2eK2FQBWh/mQQxa5jbsrtVBQiHOSBKRqsKehnPoUF9myoG39BLyXWF40f4fdlNvld3nnWQfOXmmPwizeba7CkQAk4SwALthDeyQiZOQRu805dZSN15nYMHeQYjscCtW5oMG+QdQ4hsQYGZNkYJogyc0KURnSANyFpu4RPvMvTWe0inZy+W2BlL/rKmOUspQHOkPOQbfj64gmQ4A6m53MZ5dVXWc3AraaHW54hBdFlxH3T5osjUp+s9xF+vxa8nx4J7L6qaaZxFkfKKBStpjoRlGCwAzVNZRfcUy/tdVod6XK+DmF1y84SAzBa3/hUUCEQU15AED1AFR2X2JPNqmYEnqmSeQ2zRBiW5iATw/0WsDqiqXLnk9GF8J/fuDGeyBTyf+siOw9VSAawbhBuRotWdryQeay6cPBxvrKvzRRcdUQqg84eVw/DlcgaB4F53VAoFLxSao7DUV2iWwRPLwe4vxrK8uu32vFEcrAHNR4wzmpxtu7k0WNA0GeSOAkWj30OnbDfH6YcnOHxENuVSUVxvGj3+cqGnzLb2gvXiVY20E5eDrzfM8tu9176JzGjPwkg1vLqTHJUWjlkgI7/iwoUea/xsH/yGVuPkZpsQdsctBILlhDE9PkKB3VmyFimSUh8zlhJ9rX4Fr8MPxaMT6cqbtjXln4V2rjqSFSpA8Q5umkpEDeT+BM5OX5u0qxqS72oGz7aokcIlTl7Q==
    ACCESS_SECRET_KEY: AgCNNyqtC1xgwVJaeJxLHeJ8/pZVNocQ1jgA3LVFXBwIvO+J/CU1r5Ek2ddPotnRjEEB+BWi2ZtO2+6XvDNixc4LBVgM0mfGGMpHLoBnN74d94IvmxRZwxLJDwgMrKLiygLYI2ArQr5laiKKu7SrlYEx4DDJlbvpQTZvUbunXqUROh0rR+Zcn8ZWZvDZXXxs+VyuP6t/s9ZmMkFvn+lHqw0gqCDR4pRnNWQFCY+8ww9n74yyuRVi8BqUh2Ruy6J8DkNCdQLq6Gcdi8CW9FeUKVL9nJ3XMTlYFzU/VGApgWSAXvrzhHjXniifKlun2veobqSuJgqGhyEDq5n6mQ6xeK0UiRq02Wf1vo12V65P3AhdxdgvpQaqlm9Ys+YiaPpmBz1fmfaW49LBnXyYgifhCgAvjvIkxs9/RptleCxMwVN1CpFFCY5Y5GHBa34OL6T44nOEBuq6f4YAm7/vOvmWf1Mm++g0q8ziNnizY3DcvPubXxrazgQ7SIT/iPJInrnVpVsC5q6YYZvln4G1f7rnCjhaoTyM1unHgL6PIg1O+UEIMhPJe37aCbvYSkCaIxOURNQYBOp3/ZbKQWSXhiqg4F+wyQ21rZFbNR0DWk/pGxFE5B15l9TVjImFHI337YvlHLU6YPcdr/+Yb/8MkUj2YobLASiWb3/JbETiPJXLeWIkPc02DQ7KZ5fe0tOEAPUnJmCTGdbYH06WhCxBZI3snRFlpWV2hpEvimGB3XgnjWMOuWr0tB/mV6ff
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: pg
